### ISSUE TITLE
Broken behavior with don't keep activities

### ISSUE THREAD

**Issue by eveliotc** [VictorAlbertos/RxActivityResult#1]
If you enable don't keep activities on dev settings to simulate such scenario when coming back to `MainActivity` you would get redirected once more to the camera app and then after taking another photo you get back to `MainActivity` again but it won't display the picture that was taken

**Comment by VictorAlbertos** [comment]
Hi @eveliotc

You are absolutely right. I did not take care of potential 'recreations' events. 
I've just released a [new version](https://github.com/VictorAlbertos/RxActivityResult/releases/tag/0.2) to fix this issue. 

The [docs](https://github.com/VictorAlbertos/RxActivityResult) has been updated too because some minor api changes were required.

Let me know if you find something wrong.

Thanks!
