### ISSUE TITLE
Calling startActivityForResult from service

### ISSUE THREAD

**Issue by dave08** [VictorAlbertos/RxActivityResult#32]
It would be really useful, as some Android apis require this and often need to be called from a service. To create an invisible Activity for this every time is not as nice, and also would not easily support getting the result in the service... I saw a few solutions out there...: 

http://stackoverflow.com/a/38414213
http://stackoverflow.com/a/37754232
http://stackoverflow.com/a/40356400

What do you think? This could be a possible addition to this library? 

Thanks for your great work!!

**Comment by VictorAlbertos** [comment]
Hi @dave08 thanks for the suggestion. But the library has its limitations, and that's ok. It isn't my goal (I have not the time neither the motivation) to change it from scratch just to support some edge cases (edge cases from the point of view of this library). 

Feel free to experiment on your own and if you think it is worth it just submit a PR in order to evaluate the proposal, or just clone the repo and create a new library ;)
